---
server:
  port: 9000

management:
  port: 8085
  add-application-context-header: true
  endpoints:
    web:
      base-path: /management
      exposure:
        include: info,health


#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 120000

spring.application.name: APIGateway


ribbon:
  ReadTimeout: 130000
  ConnectTimeout: 130000
  ServerListRefreshInterval: 2000
  eureka.enabled: false
  consul.enabled: true

zuul:
  routes:
    app:
      path: /app/**
      serviceId: RestService
      strip-prefix: false
    #RestService:
    #  path: /RestService/**
    #  serviceId: RestService
    #  strip-prefix: true